name: GMX Fees Tracker

on:
  schedule:
    - cron: '0 0,12,18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  track-fees:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install requests

      - name: Run GMX tracker
        run: python gmx_tracker.py

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add fees_log.csv
          git commit -m "Update fees_log.csv" || echo "No changes to commit"
          git push
