name: GMX GLP Tracker

on:
  schedule:
    - cron: '0 * * * *'  # запуск каждый час
  workflow_dispatch:  # возможность вручную запускать через GitHub

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Клонируем репозиторий
        uses: actions/checkout@v3

      - name: Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Устанавливаем зависимости
        run: pip install requests

      - name: Запускаем сбор данных
        run: python fetch_gmx_data.py
